# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-06 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=200)),
                ('owner', models.CharField(default='dummy', max_length=200)),
                ('contents', models.TextField()),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
