# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-06 10:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplelist',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 6, 10, 19, 26, 825343, tzinfo=utc)),
        ),
    ]
