# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-06 19:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0003_auto_20160806_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplelist',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 6, 19, 31, 11, 121703, tzinfo=utc)),
        ),
    ]
