# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-07 08:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0004_auto_20160806_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplelist',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 7, 8, 19, 24, 380999, tzinfo=utc)),
        ),
    ]
