# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-07 17:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0005_auto_20160807_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplelist',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 7, 17, 30, 1, 560126, tzinfo=utc)),
        ),
    ]
