# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-07 22:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0007_auto_20160807_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplelist',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 7, 22, 12, 31, 338459, tzinfo=utc)),
        ),
    ]
